USE OnlineComputerStore;

SHOW CREATE TABLE SilverAndAbove;
SHOW CREATE TABLE Customer;
SHOW CREATE TABLE StoredCard;
SHOW CREATE TABLE CreditCard;
SHOW CREATE TABLE ShippingAddress;
SHOW CREATE TABLE Cart;
SHOW CREATE TABLE AppearsIn;
SHOW CREATE TABLE OfferProduct;
SHOW CREATE TABLE Product;
SHOW CREATE TABLE Computer;
SHOW CREATE TABLE Laptop;
SHOW CREATE TABLE Printer;
